### ISSUE TITLE
First order filters question

### ISSUE THREAD

**Issue by acwiek** [adis300/filter-c#1]
Hi, is there a simple way, create a first-order filter using your code?

**Comment by adis300** [comment]
Sorry, the implementation is based on [https://exstrom.com/journal/sigproc/dsigproc.html](https://exstrom.com/journal/sigproc/dsigproc.html)

only 4,8,12,16 is supported for band pass, and 2,4,6,... for low pass and high pass.

If you really need a filter that has an odd order. You can try a similar implementation from here.
[https://exstrom.com/journal/sigproc/alpbw.c](https://exstrom.com/journal/sigproc/alpbw.c)
