### ISSUE TITLE
The high-pass filter oscillates.

### ISSUE THREAD

**Issue by KOUKILEO** [adis300/filter-c#4]
After I use a 0.5Hz high-pass filter, small signals will turn into sawtooth waves. However, if I use a 10Hz low-pass filter, there is no problem.
I use arduino external ADC and use this filter
HPF:
BWHighPass* filter = create_bw_high_pass_filter(3, 400, 0.5);
Serial.println(bw_high_pass(filter,adcv[2]),6);
![image](https://github.com/adis300/filter-c/assets/20551345/acceea57-e89c-4657-9e26-4ae4a1af177c)

LPF:
BWLowPass* filter = create_bw_low_pass_filter(3, 400, 10);
Serial.println(bw_low_pass(filter,adcv[2]),6);
![image](https://github.com/adis300/filter-c/assets/20551345/080a2f15-60d7-49f1-b27b-b1b73acfe90a)

**Comment by adis300** [comment]
Seems normal. The signal oscillates at a very small amplitude. High-pass filter allows high frequency components to stay.

> After I use a 0.5Hz high-pass filter, small signals will turn into sawtooth waves. However, if I use a 10Hz low-pass filter, there is no problem. I use arduino external ADC and use this filter HPF: BWHighPass* filter = create_bw_high_pass_filter(3, 400, 0.5); Serial.println(bw_high_pass(filter,adcv[2]),6); ![image](https://private-user-images.githubusercontent.com/20551345/296763924-acceea57-e89c-4657-9e26-4ae4a1af177c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDUwNzYsIm5iZiI6MTcwOTYwNDc3NiwicGF0aCI6Ii8yMDU1MTM0NS8yOTY3NjM5MjQtYWNjZWVhNTctZTg5Yy00NjU3LTllMjYtNGFlNGExYWYxNzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAyMTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZjFhNDE1ZGY1ODQ4MzdmZjgxYTY5ODZlOTM2NDhkZmNhZmM3NzZiN2Q2OTQ3Y2FiZTRlMGQzMTdjOGZjM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VnVHOvpv5t6aNlLmuIal1fIfHeA-e6K9Mhzu9OpmLJ0)
> 
> LPF: BWLowPass* filter = create_bw_low_pass_filter(3, 400, 10); Serial.println(bw_low_pass(filter,adcv[2]),6); ![image](https://private-user-images.githubusercontent.com/20551345/296764126-080a2f15-60d7-49f1-b27b-b1b73acfe90a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDUwNzYsIm5iZiI6MTcwOTYwNDc3NiwicGF0aCI6Ii8yMDU1MTM0NS8yOTY3NjQxMjYtMDgwYTJmMTUtNjBkNy00OWYxLWIyN2ItYjFiNzNhY2ZlOTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAyMTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1Zjg4NmY3YjI0Y2JjOTlkZTU0MzFmZWQyNzI1NTc5ZGM2ZDNhZTdiODE3YmY2NDkyNWYwNDRjOWM3ZGRlZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wje24VoDQeAiMwVjj5ZNaOl4TTxJ8AmNSx0-l_aw_hE)
